language: ruby
before_install:
  - gem install bundler

install:
  - bundle install --without debugger

script:
  - rspec spec/suite.rb

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.1.2
  - 1.9.3
matrix:
  allow_failures:
    - rvm: ruby-head
