language: ruby
before_install:
  - gem install bundler

cache: bundler

install:
  - bundle install --without debugger

script:
  - bundle exec rake spec

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.4.2
  - 2.5.0
matrix:
  allow_failures:
    - rvm: ruby-head
