language: ruby
cache: bundler
bundler_args: --without debugger
rvm:
  - 3.0.0
  - 2.7.1
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.5.0

script:
  - bundle exec rake spec

notifications:
  email:
    recipients:
      - ngiger@ywesee.com

env:
  - de_CH.UTF-8 LANGUAGE=de_CH
