language: ruby
before_install:
  - gem install bundler

cache: bundler

install:
  - bundle install --without debugger

script:
  - bundle exec rake spec

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
